### ISSUE TITLE
uninitialized constant YAML (NameError)

### ISSUE THREAD

**Issue by forrestgrant** [clayallsopp/maglev#14]
Here is my Gemfile (builds with `maglev` commented out)

``` ruby
source 'https://rubygems.org'

gem "ProMotion", :git => 'git@github.com:clearsightstudio/ProMotion.git'
gem 'motion-config-vars'
gem "maglev", :git => "git://github.com/clayallsopp/maglev.git"
```

**Comment by clayallsopp** [comment]
I'm 98% sure this is a problem with `motion-config-vars` and not maglev. There's no use or mention of `YAML` anywhere in maglev, whereas `motion-config-vars` heavily uses YAML.

If you can track down where the constant error occurs then I can help more!

**Comment by forrestgrant** [comment]
I think it's an incompatibility with ProMotion

Removing everything _except_ `maglev` builds just fine.
Adding `ProMotion` to the gem file, won't build
`ruby uninitialized constant ProMotion::TableViewCell::TableViewCellModule`

I'm going to keep looking into it, but just a heads up. Maybe good for @jamonholmgren to look at also?

**Comment by jamonholmgren** [comment]
``` bash
Searching 102 files for "YAML" (case sensitive)

0 matches across 0 files
```

Looks like it's not in ProMotion either.

**Comment by jamonholmgren** [comment]
Oh, never mind...reading comprehension issues. Switching to the other issue.

**Comment by jamonholmgren** [comment]
Maglev turns off `detect_dependencies` for your entire app. You'll need to turn it back on in your Rakefile.

``` ruby
Motion::Project::App.setup do |app|
  app.name = 'promotion_issue_278'
  app.detect_dependencies = true
end
```
